import { StyleSheet } from 'react-native';
import { typography } from '../theme/typography';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#304AA0',
  },
  staticLogoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    paddingHorizontal: 18,
  },
  tabContent: {
    flex: 1,
    overflow: 'hidden',
  },
  tabPager: {
    flex: 1,
    flexDirection: 'row',
  },
  tabPage: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  blobPrimary: {
    position: 'absolute',
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: 'rgba(244, 164, 185, 0.9)',
    top: -82,
    right: -104,
  },
  blobSecondary: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(250, 178, 198, 0.95)',
    top: 250,
    left: -52,
  },
  content: {
    paddingTop: 22,
    paddingHorizontal: 18,
    paddingBottom: 140,
  },
  iconsTab: {
    flex: 1,
    paddingTop: 0,
    paddingHorizontal: 18,
    paddingBottom: 0,
  },
  heroBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  subtitle: {
    color: '#D6E3FF',
    fontSize: 15,
    fontFamily: typography.regular,
    maxWidth: 320,
  },
  searchShell: {
    borderRadius: 17,
    backgroundColor: 'rgba(244, 248, 255, 0.96)',
    borderWidth: 0.5,
    borderColor: 'rgba(53, 83, 140, 0.2)',
    marginBottom: 8,
  },
  searchInput: {
    color: '#2A3F66',
    fontSize: 16,
    fontFamily: typography.medium,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dropdownWrap: {
    position: 'relative',
    marginBottom: 26,
  },
  dropdownButton: {
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(252, 253, 255, 0.96)',
    borderWidth: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#12265D',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  dropdownLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#DCE8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 28,
    height: 28,
  },
  dropdownButtonText: {
    color: '#161A2A',
    fontFamily: typography.semiBold,
    fontSize: 17,
  },
  dropdownChevron: {
    color: '#27334B',
    fontSize: 16,
    fontFamily: typography.medium,
    marginTop: 2,
  },
  dropdownMenu: {
    marginTop: 8,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(31, 58, 112, 0.1)',
    borderWidth: 0.5,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomColor: 'rgba(61, 108, 143, 0.12)',
    borderBottomWidth: 1,
  },
  dropdownItemText: {
    color: '#2C436A',
    fontFamily: typography.semiBold,
    fontSize: 14,
  },
  gridShell: {
    flex: 1,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
    backgroundColor: 'rgba(247, 251, 255, 0.96)',
    paddingHorizontal: 12,
    paddingTop: 18,
    paddingBottom: 0,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gridSearch: {
    justifyContent: 'flex-start',
  },
  gridList: {
    maxHeight: '100%',
  },
  gridListContent: {
    paddingBottom: 0,
  },
  gridEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 24,
  },
  gridEmptyImage: {
    width: 136,
    height: 136,
    resizeMode: 'contain',
    marginBottom: 12,
  },
  gridEmptyTitle: {
    color: '#1E2D4B',
    fontFamily: typography.bold,
    fontSize: 20,
    marginBottom: 6,
  },
  gridEmptySubtitle: {
    color: '#61779F',
    fontFamily: typography.regular,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 14,
  },
  gridEmptyActionButton: {
    borderRadius: 14,
    backgroundColor: '#304AA0',
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  gridEmptyActionLabel: {
    color: '#FFFFFF',
    fontFamily: typography.semiBold,
    fontSize: 14,
  },
  gridFooterSpacer: {
    height: 112,
  },
  settingsScroll: {
    flex: 1,
  },
  settingsContainer: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 112,
  },
  settingsSurface: {
    backgroundColor: '#ECECEC',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 20,
  },
  settingsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  settingsHeaderTitle: {
    color: '#0F172A',
    fontFamily: typography.extraBold,
    fontSize: 46,
  },
  settingsTopButton: {
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#0F172A',
    paddingHorizontal: 20,
    paddingVertical: 9,
    backgroundColor: '#EFEFEF',
  },
  settingsTopButtonLabel: {
    color: '#0F172A',
    fontFamily: typography.semiBold,
    fontSize: 14,
  },
  settingsPromoCard: {
    borderRadius: 16,
    backgroundColor: '#F7F7F7',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  settingsPromoText: {
    flex: 1,
    marginRight: 8,
  },
  settingsPromoTitle: {
    color: '#101626',
    fontFamily: typography.bold,
    fontSize: 17,
    marginBottom: 2,
  },
  settingsPromoSubtitle: {
    color: '#5B6373',
    fontFamily: typography.regular,
    fontSize: 14,
  },
  settingsSection: {
    marginBottom: 16,
    gap: 8,
  },
  sectionTitle: {
    color: '#0B1324',
    fontFamily: typography.medium,
    fontSize: 18,
    marginTop: 2,
    marginBottom: 4,
  },
  settingsSubtitle: {
    textAlign: 'left',
    color: '#51627E',
    fontSize: 13,
    fontFamily: typography.regular,
    lineHeight: 18,
    marginBottom: 2,
  },
  settingsRow: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  settingsRowLeadingIcon: {
    width: 30,
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginRight: 10,
  },
  settingsRowLabel: {
    color: '#1C2740',
    fontFamily: typography.semiBold,
    fontSize: 18,
    flex: 1,
  },
  settingsRowChevron: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  settingsRowPrimary: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  settingsRowPrimaryLabel: {
    color: '#0F172A',
    fontFamily: typography.bold,
    fontSize: 18,
    flex: 1,
  },
  launcherAccordionTitle: {
    color: '#1C2740',
    fontFamily: typography.semiBold,
    fontSize: 18,
    flex: 1,
  },
  launcherAccordion: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  launcherAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  launcherAccordionChevron: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  loaderWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  launcherList: {
    marginTop: 12,
    gap: 8,
  },
  launcherRow: {
    borderRadius: 14,
    backgroundColor: '#FAFAFA',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  launcherHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  launcherRowDisabled: {
    opacity: 0.62,
  },
  launcherName: {
    color: '#24324F',
    fontFamily: typography.semiBold,
    fontSize: 15,
  },
  launcherOpenButton: {
    borderRadius: 10,
    backgroundColor: '#EEF2FF',
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  launcherOpenButtonDisabled: {
    opacity: 0.6,
  },
  launcherOpenButtonLabel: {
    color: '#4C1D95',
    fontFamily: typography.semiBold,
    fontSize: 12,
  },
  updateSection: {
    marginTop: 0,
  },
  updateButton: {
    borderRadius: 16,
    backgroundColor: 'rgba(246, 250, 255, 0.98)',
    paddingVertical: 13,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  updateButtonLabel: {
    color: '#1E3368',
    fontFamily: typography.semiBold,
    fontSize: 15,
  },
  previewOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  previewBackdropTouch: {
    ...StyleSheet.absoluteFillObject,
  },
  previewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(10, 16, 32, 0.52)',
  },
  previewSheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#F8FBFF',
    paddingTop: 10,
    paddingBottom: 36,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  previewHandle: {
    width: 54,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#BCCCE7',
    alignSelf: 'center',
    marginBottom: 22,
  },
  previewIconWrap: {
    width: 112,
    height: 112,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E6EEF9',
    marginBottom: 16,
  },
  previewIconImage: {
    width: 92,
    height: 92,
    borderRadius: 26,
  },
  previewTitle: {
    color: '#1A2B49',
    fontFamily: typography.bold,
    fontSize: 26,
    textAlign: 'center',
  },
  feedbackOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(11, 18, 36, 0.48)',
  },
  feedbackBackdrop: {
    flex: 1,
  },
  feedbackSubmittingOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: 'rgba(248, 251, 255, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  feedbackOpeningCard: {
    minWidth: 220,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 12,
    shadowColor: '#132A67',
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
  feedbackOpeningText: {
    color: '#2F4576',
    fontFamily: typography.semiBold,
    fontSize: 14,
    textAlign: 'center',
  },
  feedbackSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#F8FBFF',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 22,
    height: '92%',
  },
  feedbackTitle: {
    color: '#0F172A',
    fontFamily: typography.bold,
    fontSize: 21,
    textAlign: 'center',
    marginBottom: 6,
  },
  feedbackSubtitle: {
    color: '#5A6B86',
    fontFamily: typography.regular,
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 12,
  },
  feedbackSearchShell: {
    borderRadius: 14,
    backgroundColor: '#EEF4FF',
    borderWidth: 1,
    borderColor: '#D7E2F5',
    marginBottom: 10,
  },
  feedbackSearchInput: {
    color: '#1D2D4A',
    fontSize: 15,
    fontFamily: typography.medium,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  feedbackListShell: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DCE6F6',
    backgroundColor: '#F4F8FF',
    flex: 1,
    overflow: 'hidden',
  },
  feedbackRow: {
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#E1E9F7',
    gap: 12,
  },
  feedbackRowDisabled: {
    opacity: 0.6,
  },
  feedbackRowMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  feedbackRowTitleWrap: {
    flex: 1,
    justifyContent: 'center',
  },
  feedbackAppIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
  },
  feedbackAppIconFallback: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#DCE6F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackAppIconFallbackText: {
    color: '#40557E',
    fontFamily: typography.bold,
    fontSize: 16,
  },
  feedbackRowTitle: {
    color: '#1B2A45',
    fontFamily: typography.semiBold,
    fontSize: 15,
    flex: 1,
  },
  feedbackRowTitleDisabled: {
    color: '#60728F',
  },
  feedbackRowStatusLabel: {
    color: '#8094B4',
    fontFamily: typography.medium,
    fontSize: 11,
    marginTop: 2,
  },
  feedbackCheckbox: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackEmptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    gap: 12,
  },
  feedbackEmptyTitle: {
    color: '#445570',
    fontFamily: typography.semiBold,
    fontSize: 15,
    textAlign: 'center',
  },
  feedbackEmptyReload: {
    borderRadius: 10,
    backgroundColor: '#E8F0FF',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  feedbackEmptyReloadLabel: {
    color: '#2E4D86',
    fontFamily: typography.semiBold,
    fontSize: 13,
  },
  feedbackActions: {
    flexDirection: 'row',
    width: 190,
    alignSelf: 'center',
    marginTop: 14,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    padding: 5,
    shadowColor: '#132A67',
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  feedbackActionButton: {
    flex: 1,
    borderRadius: 999,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackActionSecondary: {
    backgroundColor: 'transparent',
  },
  feedbackActionPrimary: {
    backgroundColor: '#F2F4F8',
  },
  feedbackActionPrimaryDisabled: {
    opacity: 0.65,
  },
  feedbackActionSecondaryLabel: {
    color: '#37517D',
    fontFamily: typography.semiBold,
    fontSize: 14,
  },
  feedbackActionPrimaryLabel: {
    color: '#FFFFFF',
    fontFamily: typography.bold,
    fontSize: 14,
  },
  feedbackSuccessSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: '#F8FBFF',
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 28,
    alignItems: 'center',
  },
  feedbackSuccessImage: {
    width: 140,
    height: 140,
    resizeMode: 'contain',
    marginBottom: 12,
  },
  feedbackSuccessTitle: {
    color: '#1B2A45',
    fontFamily: typography.bold,
    fontSize: 20,
    textAlign: 'center',
    marginBottom: 16,
  },
  feedbackErrorMessage: {
    color: '#5A6B86',
    fontFamily: typography.regular,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  feedbackSuccessButton: {
    borderRadius: 14,
    backgroundColor: '#304AA0',
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  feedbackSuccessButtonLabel: {
    color: '#FFFFFF',
    fontFamily: typography.semiBold,
    fontSize: 14,
  },
  bottomBarShell: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 16,
    alignItems: 'center',
    zIndex: 30,
    elevation: 30,
  },
  bottomBar: {
    position: 'relative',
    flexDirection: 'row',
    width: 190,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    padding: 5,
    shadowColor: '#132A67',
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  bottomBarActivePill: {
    position: 'absolute',
    top: 5,
    bottom: 5,
    left: 5,
    borderRadius: 999,
    backgroundColor: '#F2F4F8',
  },
  tabButton: {
    flex: 1,
    borderRadius: 999,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
});
