import { StyleSheet } from 'react-native';
import { typography } from '../theme/typography';

export const settingsStyles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  container: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 0,
  },
  surface: {
    flex: 1,
    backgroundColor: 'rgba(247, 251, 255, 0.96)',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingTop: 18,
    paddingBottom: 0,
  },
  headerRow: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 12,
    minHeight: 48,
  },
  headerTitle: {
    color: '#0F172A',
    fontFamily: typography.extraBold,
    fontSize: 24,
    textAlign: 'left',
  },
  topButton: {
    position: 'absolute',
    right: 0,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#132A67',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#FFFFFF',
  },
  topButtonLabel: {
    color: '#24324F',
    fontFamily: typography.semiBold,
    fontSize: 15,
  },
  promoCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E5EAF5',
  },
  promoText: {
    flex: 1,
    marginRight: 8,
  },
  promoTitle: {
    color: '#101626',
    fontFamily: typography.bold,
    fontSize: 17,
    marginBottom: 2,
  },
  promoSubtitle: {
    color: '#5B6373',
    fontFamily: typography.regular,
    fontSize: 14,
  },
  section: {
    marginBottom: 16,
    gap: 8,
  },
  sectionTitle: {
    color: '#0B1324',
    fontFamily: typography.medium,
    fontSize: 18,
    marginTop: 2,
    marginBottom: 4,
  },
  row: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  rowPrimary: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  rowLeadingIcon: {
    width: 30,
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginRight: 10,
  },
  rowLabel: {
    color: '#1C2740',
    fontFamily: typography.semiBold,
    fontSize: 18,
    flex: 1,
  },
  rowPrimaryLabel: {
    color: '#0F172A',
    fontFamily: typography.bold,
    fontSize: 18,
    flex: 1,
  },
  rowChevron: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  launcherAccordion: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  launcherAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  launcherAccordionTitle: {
    color: '#1C2740',
    fontFamily: typography.semiBold,
    fontSize: 18,
    flex: 1,
  },
  launcherAccordionChevron: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  loaderWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  launcherList: {
    marginTop: 12,
    gap: 8,
  },
  launcherRow: {
    borderRadius: 14,
    backgroundColor: '#FAFAFA',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  launcherRowDisabled: {
    opacity: 0.62,
  },
  launcherHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  launcherName: {
    color: '#24324F',
    fontFamily: typography.semiBold,
    fontSize: 15,
  },
  launcherOpenButton: {
    borderRadius: 10,
    backgroundColor: '#EEF3FB',
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  launcherOpenButtonDisabled: {
    opacity: 0.6,
  },
  launcherOpenButtonLabel: {
    color: '#31486D',
    fontFamily: typography.semiBold,
    fontSize: 12,
  },
});
