import { ImageSourcePropType } from 'react-native';

// Auto-generated by scripts/generate-gallery-manifest.js — do not edit by hand.
// Each value is an Android drawable-resource URI; React Native resolves the bare
// name to res/drawable-nodpi/<name>.webp, so the grid reuses the launcher icons
// with zero duplicated image bytes.
export const iconImageMap: Record<string, ImageSourcePropType> = {

};
