export const launcherManualPaths: Record<string, string> = {
  nova: 'Nova Settings -> Look & feel -> Icon style -> Icon theme -> Disco',
  lawnchair: 'Lawnchair Settings -> Theme -> Icon Pack -> Disco',
  hyperion: 'Hyperion Settings -> Icons -> Icon pack -> Disco',
  apex: 'Apex Settings -> Theme settings -> Icon pack -> Disco',
  action: 'Action Launcher Settings -> Appearance -> Icon Pack -> Disco',
  smart: 'Smart Launcher Settings -> Themes -> Icon Pack -> Disco',
  adw: 'ADW Settings -> Themes -> Icon Pack -> Disco',
  poco: 'POCO Launcher Settings -> Icon pack -> Disco',
  niagara: 'Niagara Settings -> Look -> Icon Pack -> Disco',
  total: 'Total Launcher Settings -> Icon -> Icon Pack -> Disco',
  lynx: 'Lynx Launcher Settings -> Icons -> Icon Pack -> Disco',
  moto: 'Moto Launcher Settings -> Home settings -> Icon style -> Disco',
  samsung: 'Samsung One UI Home Settings -> Themes -> Icons -> Disco',
  nothing: 'Home -> Customization -> Icon pack -> Disco',
};
